---
- name: Preparation for setup of raspberrypi
  hosts: localhost
  connection: local"
  tasks:

    - name: Install packages
      ansible.builtin.package:
        name:
          - git
          - docker
          - iptables
        state: latest

    - name: Creating cmdline.txt with extra content
      copy:
        dest: /boot/cmdline.txt
        force: true
        content: "{{lookup('ansible.builtin.file', '/boot/cmdline.txt') }} cgroup_enable=memory cgroup_memory=1"

    - name: Set iptables from nat to legacy
      ansible.builtin.shell: |
          iptables -F
          update-alternatives --set iptables /usr/sbin/iptables-legacy

    # - name: Reboot
    #   ansible.builtin.reboot: